# These are supported funding model platforms

github: #muneebwanee,thedeepnet
patreon: #muneebwanee
open_collective: #muneebwanee
ko_fi: #muneebwanee
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: #muneebwanee
issuehunt: #muneebwanee
otechie: #muneebwanee
custom: #'muneebwanee.blogspot.com', 'tdeepnet.blogspot.com']
